// Demo verileri - Social Proof için

export const stats = [
  { value: '500+', label: 'Aktif Öğrenci' },
  { value: '50+', label: 'Uzman Koç' },
  { value: '10.000+', label: 'Tamamlanan Görev' },
  { value: '4.9', label: 'Ortalama Puan' },
]

export const testimonials = [
  {
    id: 1,
    name: 'Elif Yılmaz',
    school: 'Galatasaray Lisesi',
    grade: '12. Sınıf',
    avatar: null,
    rating: 5,
    text: 'Koçum sayesinde TYT netlerim 3 ayda 40\'tan 75\'e çıktı. Özellikle matematik konusunda harika yönlendirmeler aldım.',
    examType: 'TYT',
    improvement: '+35 net',
  },
  {
    id: 2,
    name: 'Ahmet Kaya',
    school: 'Kabataş Erkek Lisesi',
    grade: '11. Sınıf',
    avatar: null,
    rating: 5,
    text: 'Yapay zeka destekli analiz sayesinde eksiklerimi çok net gördüm. Artık hangi konuya ne kadar çalışacağımı biliyorum.',
    examType: 'AYT',
    improvement: '+28 net',
  },
  {
    id: 3,
    name: 'Zeynep Demir',
    school: 'TED Ankara Koleji',
    grade: '12. Sınıf',
    avatar: null,
    rating: 5,
    text: 'Deneme sonuçlarımı yükleyip anında analiz alabilmek muhteşem. Koçumla birlikte hazırladığımız plan sayesinde Tıp Fakültesi hedefime çok yaklaştım.',
    examType: 'TYT/AYT',
    improvement: 'Tıp hedefi',
  },
  {
    id: 4,
    name: 'Mert Özkan',
    school: 'Robert Koleji',
    grade: '12. Sınıf',
    avatar: null,
    rating: 5,
    text: 'Haftalık görevler ve düzenli takip motivasyonumu yükseltti. Özellikle Fen Bilimleri konusunda çok ilerleme kaydettim.',
    examType: 'AYT',
    improvement: '+42 net',
  },
  {
    id: 5,
    name: 'Sude Arslan',
    school: 'Atatürk Anadolu Lisesi',
    grade: '11. Sınıf',
    avatar: null,
    rating: 5,
    text: 'Velim olarak çocuğumun gelişimini takip edebiliyorum. Koç ile sürekli iletişim halindeyiz, çok memnunuz.',
    examType: 'LGS',
    improvement: 'Veli görüşü',
  },
  {
    id: 6,
    name: 'Can Yıldırım',
    school: 'Eyüboğlu Koleji',
    grade: '8. Sınıf',
    avatar: null,
    rating: 5,
    text: 'LGS\'de ilk 1000\'e girmek istiyorum ve koçum bu hedef için harika bir plan hazırladı. Her hafta ilerliyorum!',
    examType: 'LGS',
    improvement: '+45 puan',
  },
]

export const activityMessages = [
  { name: 'Ahmet K.', action: 'yeni bir koç ile eşleşti', icon: 'match', time: '2 dk önce' },
  { name: 'Elif Y.', action: '85 net yaptı', icon: 'score', time: '5 dk önce' },
  { name: 'Mert Ö.', action: 'görevini tamamladı', icon: 'task', time: '8 dk önce' },
  { name: 'Zeynep D.', action: 'yeni kayıt oldu', icon: 'register', time: '12 dk önce' },
  { name: 'Can Y.', action: 'deneme sonucu yükledi', icon: 'exam', time: '15 dk önce' },
  { name: 'Sude A.', action: '92 net ile rekor kırdı', icon: 'trophy', time: '18 dk önce' },
  { name: 'Burak T.', action: 'koçundan mesaj aldı', icon: 'message', time: '22 dk önce' },
  { name: 'Ayşe S.', action: 'çalışma planı oluşturdu', icon: 'plan', time: '25 dk önce' },
]

export const universities = [
  { name: 'İstanbul Teknik Üniversitesi', abbr: 'İTÜ', url: 'https://www.itu.edu.tr', color: 'from-red-500 to-red-600' },
  { name: 'Boğaziçi Üniversitesi', abbr: 'BÜ', url: 'https://www.boun.edu.tr', color: 'from-blue-600 to-blue-700' },
  { name: 'Orta Doğu Teknik Üniversitesi', abbr: 'ODTÜ', url: 'https://www.metu.edu.tr', color: 'from-red-600 to-orange-600' },
  { name: 'Hacettepe Üniversitesi', abbr: 'HÜ', url: 'https://www.hacettepe.edu.tr', color: 'from-orange-500 to-amber-500' },
  { name: 'Koç Üniversitesi', abbr: 'KOÇ', url: 'https://www.ku.edu.tr', color: 'from-blue-500 to-indigo-600' },
  { name: 'Sabancı Üniversitesi', abbr: 'SÜ', url: 'https://www.sabanciuniv.edu', color: 'from-purple-500 to-violet-600' },
  { name: 'Bilkent Üniversitesi', abbr: 'BİL', url: 'https://www.bilkent.edu.tr', color: 'from-sky-500 to-blue-600' },
  { name: 'Yıldız Teknik Üniversitesi', abbr: 'YTÜ', url: 'https://www.yildiz.edu.tr', color: 'from-yellow-500 to-orange-500' },
  { name: 'Ankara Üniversitesi', abbr: 'AÜ', url: 'https://www.ankara.edu.tr', color: 'from-emerald-500 to-teal-600' },
  { name: 'Ege Üniversitesi', abbr: 'EÜ', url: 'https://www.ege.edu.tr', color: 'from-cyan-500 to-blue-500' },
  { name: 'Galatasaray Üniversitesi', abbr: 'GSÜ', url: 'https://www.gsu.edu.tr', color: 'from-red-500 to-yellow-500' },
  { name: 'Marmara Üniversitesi', abbr: 'MÜ', url: 'https://www.marmara.edu.tr', color: 'from-indigo-500 to-purple-600' },
]

export const demoCoaches = [
  {
    full_name: 'Dr. Ayşe Kara',
    headline: 'Matematik & Geometri Uzmanı',
    bio: '15 yıllık deneyimle binlerce öğrenciyi üniversiteye hazırladım. ODTÜ Matematik mezunuyum. Öğrencilerimin %90\'ı hedefledikleri bölüme yerleşti.',
    specializations: ['Matematik', 'Geometri', 'TYT'],
    hourly_rate: 350,
    experience_years: 15,
    student_count: 120,
    rating: 4.9,
    review_count: 87,
  },
  {
    full_name: 'Prof. Mehmet Yılmaz',
    headline: 'Fizik & Fen Bilimleri Koçu',
    bio: 'İTÜ Fizik Bölümü öğretim üyesiyim. Karmaşık konuları basit ve anlaşılır hale getirmekte uzmanım. Online eğitimde 5+ yıl tecrübem var.',
    specializations: ['Fizik', 'Fen Bilimleri', 'AYT'],
    hourly_rate: 400,
    experience_years: 20,
    student_count: 200,
    rating: 4.95,
    review_count: 156,
  },
  {
    full_name: 'Zehra Demir',
    headline: 'Türkçe & Edebiyat Uzmanı',
    bio: 'Boğaziçi Türk Dili ve Edebiyatı mezunuyum. Paragraf ve dil bilgisi konularında öğrencilerimin netleri ortalama %40 artış gösteriyor.',
    specializations: ['Türkçe', 'Edebiyat', 'TYT'],
    hourly_rate: 300,
    experience_years: 12,
    student_count: 95,
    rating: 4.85,
    review_count: 72,
  },
  {
    full_name: 'Ali Rıza Öztürk',
    headline: 'Kimya & Biyoloji Koçu',
    bio: 'Hacettepe Tıp Fakültesi mezunuyum. Tıp, Diş Hekimliği ve Eczacılık hedefleyen öğrencilere özel hazırlık programları sunuyorum.',
    specializations: ['Kimya', 'Biyoloji', 'AYT'],
    hourly_rate: 380,
    experience_years: 10,
    student_count: 85,
    rating: 4.9,
    review_count: 63,
  },
  {
    full_name: 'Deniz Aydın',
    headline: 'LGS Uzmanı & Motivasyon Koçu',
    bio: 'Çocuk psikolojisi eğitimim var. LGS\'ye hazırlanan öğrencilere hem akademik hem de psikolojik destek sağlıyorum.',
    specializations: ['LGS', 'Motivasyon', 'Çalışma Teknikleri'],
    hourly_rate: 280,
    experience_years: 8,
    student_count: 150,
    rating: 4.88,
    review_count: 98,
  },
  {
    full_name: 'Selin Koç',
    headline: 'Tarih & Sosyal Bilimler Uzmanı',
    bio: 'Ankara Üniversitesi Tarih Bölümü mezunuyum. Ezbere dayalı değil, anlayarak öğrenmeyi öğretiyorum. YKS Sosyal netleri garantili artırıyorum.',
    specializations: ['Tarih', 'Coğrafya', 'Felsefe'],
    hourly_rate: 290,
    experience_years: 9,
    student_count: 110,
    rating: 4.82,
    review_count: 54,
  },
  {
    full_name: 'Emre Yıldız',
    headline: 'İngilizce & Yabancı Dil Koçu',
    bio: 'Cambridge sertifikalı İngilizce eğitmeniyim. YDS, YÖKDİL ve YKS İngilizce sınavlarına hazırlık konusunda uzmanım.',
    specializations: ['İngilizce', 'YDS', 'YÖKDİL'],
    hourly_rate: 320,
    experience_years: 11,
    student_count: 180,
    rating: 4.92,
    review_count: 121,
  },
  {
    full_name: 'Büşra Aktaş',
    headline: 'Sayısal & Eşit Ağırlık Koçu',
    bio: 'Bilkent Endüstri Mühendisliği mezunuyum. Öğrencilerin potansiyelini keşfedip doğru bölüm seçiminde rehberlik ediyorum.',
    specializations: ['Matematik', 'Problem Çözme', 'Kariyer Danışmanlığı'],
    hourly_rate: 340,
    experience_years: 7,
    student_count: 75,
    rating: 4.87,
    review_count: 48,
  },
]

